#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

fileList=$(git diff --diff-filter=d --cached --name-only)
set +e
files=$(echo "$fileList" | grep -E '\.(liquid)$')
set -e

# if [ ${#files} -gt 0 ]; then
if [ -n "$files" ]; then
  # Lintスタート
  echo 'Start prettier.'
  npm run prettier -- ${files[*]} "$@" --write
  # エラーがあれば、コミットさせない
  if [ $? -gt 0 ]; then
    exit 1
  fi
  # エラーがなければ、Linterが変更した差分を取り込んでコミット
  git add ${files[@]}
fi
